# Generated by Django 4.1 on 2023-05-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="settings_model",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_settings",
                    models.IntegerField(blank=True, default=1, null=True, unique=True),
                ),
                (
                    "attendance_update_time_min",
                    models.IntegerField(blank=True, default=30, null=True, unique=True),
                ),
                (
                    "head_turn_count",
                    models.IntegerField(blank=True, default=7, null=True, unique=True),
                ),
                (
                    "head_count_time_sec",
                    models.IntegerField(blank=True, default=60, null=True, unique=True),
                ),
            ],
        ),
    ]
