# Generated by Django 4.1 on 2023-05-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamapp", "0002_settings_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings_model",
            name="left_head_threshHold",
            field=models.IntegerField(blank=True, default=-6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="settings_model",
            name="right_head_threshHold",
            field=models.IntegerField(blank=True, default=6, null=True, unique=True),
        ),
    ]
