# Generated by Django 4.1 on 2023-05-27 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("streamapp", "0003_settings_model_left_head_threshhold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings_model",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
