# Generated by Django 4.1 on 2023-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamapp", "0004_settings_model_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings_model",
            name="head_count_time_sec",
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
        migrations.AlterField(
            model_name="settings_model",
            name="head_turn_count",
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AlterField(
            model_name="settings_model",
            name="left_head_threshHold",
            field=models.IntegerField(blank=True, default=-6, null=True),
        ),
        migrations.AlterField(
            model_name="settings_model",
            name="right_head_threshHold",
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
    ]
