# Generated by Django 4.1 on 2023-05-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamapp", "0005_alter_settings_model_head_count_time_sec_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="settings_model", name="id",),
        migrations.AlterField(
            model_name="settings_model",
            name="attendance_update_time_min",
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name="settings_model",
            name="id_settings",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
