# Generated by Django 4.1 on 2023-07-11 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamapp", "0007_profile_image_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile_image",
            name="name",
            field=models.CharField(
                blank=True,
                default="None",
                max_length=122,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z]*$", "Only alphabets are allowed."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile_image",
            name="roll_num",
            field=models.IntegerField(
                blank=True,
                unique=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="settings_model",
            name="attendance_update_time_min",
            field=models.IntegerField(
                blank=True,
                default=30,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="settings_model",
            name="head_count_time_sec",
            field=models.IntegerField(
                blank=True,
                default=60,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="settings_model",
            name="head_turn_count",
            field=models.IntegerField(
                blank=True,
                default=7,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="settings_model",
            name="left_head_threshHold",
            field=models.IntegerField(
                blank=True,
                default=-6,
                null=True,
                validators=[django.core.validators.MaxValueValidator(-1)],
            ),
        ),
        migrations.AlterField(
            model_name="settings_model",
            name="right_head_threshHold",
            field=models.IntegerField(
                blank=True,
                default=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
