# Generated by Django 4.1 on 2023-07-12 17:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamapp", "0008_alter_profile_image_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings_model",
            name="head_count_time_sec",
            field=models.IntegerField(
                blank=True,
                default=60,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3600),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings_model",
            name="head_turn_count",
            field=models.IntegerField(
                blank=True,
                default=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings_model",
            name="left_head_threshHold",
            field=models.IntegerField(
                blank=True,
                default=-6,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(-1),
                    django.core.validators.MinValueValidator(-50),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="settings_model",
            name="right_head_threshHold",
            field=models.IntegerField(
                blank=True,
                default=6,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(50),
                ],
            ),
        ),
    ]
