# Generated by Django 4.1 on 2023-07-13 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("streamapp", "0009_alter_settings_model_head_count_time_sec_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile_image",
            name="name",
            field=models.CharField(
                blank=True,
                default="None",
                max_length=122,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z\\s]*$", "Only alphabets are allowed."
                    )
                ],
            ),
        ),
    ]
